import {
  FileText,
  Settings,
  ShieldAlert,
  User2,
  Truck,
  Crown,
  Zap,
  LayoutDashboard,
  ShoppingCart,
  Package,
  Users,
  Megaphone,
  Image,
  Shield,
  Server,
  LifeBuoy,
  Sparkles,
  MessageSquare,
  Target,
  Star,
  LayoutGrid,
  Briefcase,
  BookOpen,
  Lock,
  BarChart,
  CheckCircle2,
  XCircle,
  ShieldCheck,
  SlidersHorizontal,
  Bell,
  CreditCard,
  User,
  Bike,
  Rocket,
  PackageCheck,
} from "lucide-react";
import { FeaturePermission } from "@/constants/feature-permission";
import { UserSearchIcon } from "lucide-react";
import { Settings2Icon } from "lucide-react";
import { Settings2 } from "lucide-react";

// Navigation organized by sections and workflow
// title: used for iconMap lookup; tKey: translation key for i18n
export const navSections = [
  {
    id: "main",
    title: "General",
    tKey: "nav.main",
    icon: LayoutDashboard,
    items: [
      {
        id: 1.6,
        title: "AI Daily Report",
        tKey: "nav.aiDailyReport",
        link: "/ai-report",
        icon: Sparkles,
      },
      {
        id: 1.65,
        title: "Media",
        tKey: "nav.media",
        link: "/media",
        icon: Image,
      },
      {
        id: 1.7,
        title: "AI Live Feed",
        tKey: "nav.aiLiveFeed",
        link: "/ai-live-feed",
        icon: MessageSquare,
      },
      {
        id: 1.8,
        title: "AI Sales Direction",
        tKey: "nav.aiSalesDirection",
        link: "/ai-sales-direction",
        icon: Target,
      },
      {
        id: 1.9,
        title: "Statistics",
        tKey: "nav.statistics",
        link: "/statistics",
        icon: Star,
      },
    ],
  },
  {
    id: "orders",
    title: "Order Management",
    tKey: "nav.orderManagement",
    icon: ShoppingCart,
    items: [
      {
        id: 6,
        title: "Order",
        tKey: "nav.order",
        link: "/orders",
        permission: FeaturePermission.ORDERS,
        icon: ShoppingCart,
      },

      {
        id: 7.0,
        title: "Credit Notes",
        tKey: "nav.creditNotes",
        link: "/credit-notes",
        permission: FeaturePermission.ORDERS,
        icon: FileText,
      },
      {
        id: 7.5,
        title: "Courier",
        tKey: "nav.courier",
        icon: Truck,
        children: [
          {
            title: "Steadfast Courier",
            tKey: "nav.steadfastCourier",
            link: "/steadfast",
            permission: FeaturePermission.STEARDFAST,
            icon: PackageCheck,
          },
          {
            title: "Pathao Courier",
            tKey: "nav.pathaoCourier",
            link: "/pathao",
            permission: FeaturePermission.PATHAO,
            icon: Bike,
          },
          {
            title: "RedX Courier",
            tKey: "nav.redxCourier",
            link: "/redx",
            permission: FeaturePermission.REDX,
            icon: Rocket,
          },
        ],
      },
      {
        id: 7.8,
        title: "Fraud Checker",
        tKey: "nav.fraudChecker",
        link: "/fraud",
        permission: FeaturePermission.REPORTS,
        icon: ShieldAlert,
      },
    ],
  },
  {
    id: "invoices",
    title: "Invoice Management",
    tKey: "Invoice Management",
    icon: FileText,
    items: [
      {
        id: 6.51,
        title: "Invoice List",
        tKey: "Invoice List",
        link: "/invoices",
        permission: FeaturePermission.ORDERS,
        icon: FileText,
      },
      {
        id: 6.52,
        title: "Recurring Invoices",
        tKey: "Recurring Invoices",
        link: "/recurring-invoices",
        permission: FeaturePermission.ORDERS,
        icon: FileText,
      },
    ],
  },
  {
    id: "products",
    title: "Inventory Management",
    tKey: "nav.productManagement",
    icon: Package,
    items: [
      {
        id: 6,
        title: "Product",
        tKey: "nav.product",
        link: "/products",
        permission: FeaturePermission.PRODUCTS,
        icon: Package,
      },
      {
        id: 7,
        title: "Categories",
        tKey: "nav.categories",
        link: "/categories",
        permission: FeaturePermission.CATEGORY,
        icon: FileText,
      },
      {
        id: 7.5,
        title: "Inventory",
        tKey: "nav.inventory",
        link: "/inventory",
        permission: FeaturePermission.PRODUCTS,
        icon: Package,
      },
      {
        id: 8,
        title: "Flash Sell",
        tKey: "nav.flashSell",
        link: "/flash-sell",
        permission: FeaturePermission.PRODUCTS,
        icon: Zap,
      },
    ],
  },
  {
    id: "customers",
    title: "Customer Management",
    tKey: "nav.customerManagement",
    icon: Users,
    items: [
      {
        id: 9,
        title: "Customers",
        tKey: "nav.customers",
        link: "/customers",
        permission: FeaturePermission.CUSTOMERS,
        icon: Users,
      },
      {
        id: 9.5,
        title: "Reviews",
        tKey: "nav.reviews",
        link: "/reviews",
        permission: FeaturePermission.CUSTOMERS,
        icon: Star,
      },
    ],
  },
  {
    id: "marketing",
    title: "Marketing",
    tKey: "nav.marketingPromotions",
    icon: Megaphone,
    items: [
      {
        id: 10,
        title: "Banners",
        tKey: "nav.banners",
        link: "/banners",
        permission: FeaturePermission.SETTINGS,
        icon: Megaphone,
      },
      {
        id: 11,
        title: "Promocodes",
        tKey: "nav.promocodes",
        link: "/promocodes",
        permission: FeaturePermission.SETTINGS,
        icon: Megaphone,
      },
      {
        id: 11.5,
        title: "Banners & Offers",
        tKey: "nav.bannersOffers",
        link: "/banners-offers",
        icon: Megaphone,
      },
    ],
  },
  {
    id: "content",
    title: "Content & Policy",
    tKey: "nav.contentPolicy",
    icon: BookOpen,
    items: [
      {
        id: 12,
        title: "Privacy Policy",
        tKey: "nav.privacyPolicy",
        link: "/privacy-policy",
        permission: FeaturePermission.PRIVACY_POLICY,
        icon: Shield,
      },
      {
        id: 13,
        title: "Terms & Conditions",
        tKey: "nav.termsConditions",
        link: "/terms-conditions",
        permission: FeaturePermission.TERMS_CONDITIONS,
        icon: FileText,
      },
      {
        id: 14,
        title: "Refund Policy",
        tKey: "nav.refundPolicy",
        link: "/refund-policy",
        permission: FeaturePermission.REFUND_POLICY,
        icon: FileText,
      },
    ],
  },
  {
    id: "system",
    title: "Admin",
    tKey: "nav.system",
    icon: Lock,
    items: [
      {
        id: 15,
        title: "Manage Users",
        tKey: "nav.manageUsers",
        link: "/manage-users",
        permission: FeaturePermission.STAFF,
        icon: UserSearchIcon,
        children: [
          {
            title: "All Users",
            link: "/manage-users?tab=all-users",
            icon: Users,
          },
          {
            title: "Active",
            link: "/manage-users?tab=active",
            icon: CheckCircle2,
          },
          {
            title: "Inactive",
            link: "/manage-users?tab=inactive",
            icon: XCircle,
          },
          {
            title: "System Owner",
            link: "/manage-users?tab=system-owner",
            icon: Shield,
          },
          {
            title: "Admins",
            link: "/manage-users?tab=admins",
            icon: ShieldCheck,
          },
          {
            title: "Employees",
            link: "/manage-users?tab=employees",
            icon: Briefcase,
          },
        ],
      },
      {
        id: 16,
        title: "Settings",
        tKey: "nav.settings",
        link: "/settings",
        icon: Settings2,
        children: [
          {
            title: "General",
            link: "/settings?tab=general",
            icon: Settings,
          },
          {
            title: "Preferences",
            link: "/settings?tab=preferences",
            icon: SlidersHorizontal,
          },
          {
            title: "Account",
            link: "/settings?tab=account",
            icon: User,
          },
          {
            title: "Billings",
            link: "/settings?tab=billings",
            icon: CreditCard,
          },
          {
            title: "Notifications",
            link: "/settings?tab=notifications",
            icon: Bell,
          },
        ],
      },

      {
        id: 17,
        title: "Upgrade Plan",
        tKey: "nav.upgradePlan",
        link: "/upgrade-plan",
        icon: Crown,
      },
      {
        id: 18,
        title: "Help",
        tKey: "nav.help",
        link: "/help",
        icon: LifeBuoy,
      },
    ],
  },
  {
    id: "integrations",
    title: "Reports",
    tKey: "nav.integrations",
    icon: BarChart,
    items: [
      {
        id: 19,
        title: "Connected Apps",
        tKey: "nav.connectedApps",
        link: "/connected-apps",
        icon: LayoutGrid,
      },
    ],
  },
];

// Flattened navLinks for backward compatibility
export const navLinks = navSections.flatMap((section) => section.items);

export const DROPDOWN_NAV_ITEMS = [
  {
    title: "Personal Information",
    link: "/settings/personal-information",
    icon: User2,
  },
  { title: "Settings", link: "/settings/account-security", icon: Settings },
];
